Added additional files to github workflow
polarislabs/eslint-config-polaris pull request #26
Opened 2021-01-20 00:32 UTC by brettdavis4

2021-01-20 15:47 UTC, korymarks approved these changes
LGTM

2021-01-25 15:45 UTC, babennettdev requested changes
Brett, these look good, but I'm curious if we should use `npm install` or `npm ci` for installing dependencies. Thoughts?

2021-01-25 15:45 UTC, babennettdev commented on .github/workflows/code-checks.yml
> +        run: npm install
`npm install` or `npm ci`?

2021-01-25 15:45 UTC, babennettdev commented on .github/workflows/publish-package.yml
> +        run: npm install
`npm install` or `npm ci`?

2021-01-26 21:18 UTC, brettdavis4 commented on .github/workflows/code-checks.yml
> +        run: npm install
@dbirks and I talked about this and it's been changed to npm ci.

2021-01-26 21:18 UTC, brettdavis4 commented on .github/workflows/publish-package.yml
> +        run: npm install
It's been changed to npm ci.

2021-02-05 01:33 UTC, dbirks requested changes
Cool, I could only find one small thing, thanks!

2021-02-05 01:33 UTC, dbirks commented on .github/workflows/code-checks.yml
> +      - master
I think we can run the code checks on PR's to develop as well.

2021-02-05 19:21 UTC, brettdavis4 commented on .github/workflows/code-checks.yml
> +      - master
I've added develop to the branches list.

2021-02-05 20:11 UTC, dbirks commented on .github/workflows/code-checks.yml
> +      - master
Nice, thanks :+1:

2021-02-05 20:12 UTC, dbirks approved these changes

2021-02-05 21:09 UTC, brettdavis4 commented on .github/workflows/code-checks.yml
> +        run: npm install
I've made the change.  Can you please approve it?  thanks!

2021-02-05 21:18 UTC, babennettdev approved these changes
Thanks for updating to `npm ci` 👍 Looks good.

2021-02-05 21:45 UTC, merged