Tech/fix rule relating to react
polarislabs/eslint-config-polaris pull request #28
Opened 2021-03-30 19:55 UTC by camoore1979

2021-03-31 22:27 UTC, khgriffi259 commented on react.js
> +      '@typescript-eslint/explicit-function-return-type': 'off'
Do we want this off?

2021-04-01 20:59 UTC, tshelton5000 requested changes
This works great, @camoore1979 in both HPAPI and polaris-ui-reference.  I am only holding the approval for the question first raised by @khgriffi259 .  

Thank you for the diligence in helping keep our code standards high!

2021-04-01 20:59 UTC, tshelton5000 commented on .github/auto_assign.yml
> +numberOfReviewers: 2
👍

2021-04-01 20:59 UTC, tshelton5000 commented on react.js
> +    'react/jsx-filename-extension': [1, { 'extensions': ['.jsx', '.tsx'] }],
We need a linter for our linting package ;)

2021-04-01 20:59 UTC, tshelton5000 commented on react.js
> +      '@typescript-eslint/explicit-function-return-type': 'off'
I'm with @khgriffi259 on this particular rule--I would favor adding this to `common` under the overrides for test files.  Typing inline functions rarely causes problems, and it's usually less hairy than named functions or lambdas.

2021-04-02 21:26 UTC, camoore1979 commented on react.js
> +      '@typescript-eslint/explicit-function-return-type': 'off'
Honestly, I'm not sure why these are there at all... these are overrides for *.js files (not .ts) and those shouldn't even apply at all, they are from `@typescript-eslint` so I wonder if they're leftover rules from previous problems...

2021-04-02 21:27 UTC, camoore1979 commented on react.js
> +    'react/jsx-filename-extension': [1, { 'extensions': ['.jsx', '.tsx'] }],
😁  Yep. I thought the same funny thing... and then like, what would lint the linter that lints the linter?

2021-04-03 14:12 UTC, camoore1979 commented on react.js
> +      '@typescript-eslint/explicit-function-return-type': 'off'
They are not leftover rules and they need to be maintained. For some reason, on *.js files in our React clients (such as next.config.js), these errors/warnings occur unless these rules are turned off in the overrides for *.js files. There is likely a deeper reason why this is the case, but not sure what it is, and I can't get to it right now. Adding these here is not a change to what we were doing in the client, it's simply moving the rule from the client repo to this shared package.

2021-04-03 14:13 UTC, camoore1979 commented
@tshelton5000 @khgriffi259 I've updated a few things and kicked back up for review.

2021-04-05 12:48 UTC, tshelton5000 approved these changes
Looks great to me, Chad.  Thanks for the update!

2021-04-05 13:40 UTC, khgriffi259 approved these changes
Thanks for clarifying Chad. I have approved.

2021-04-05 15:15 UTC, merged