DIS-1596 Update typescript and other dependencies
polarislabs/eslint-config-polaris pull request #35
Opened 2021-07-06 18:35 UTC by dbirks

Opening a WIP PR while I'm making sure this works with all the downstream projects.

2021-07-12 15:44 UTC, khgriffi259 submitted a review, later dismissed
LGTM!

2021-07-13 14:01 UTC, babennettdev requested changes
I did a test run of this beta package in `aurora-service` and it looked almost perfect with the exception of the `@typescript-eslint/camelcase` rule.

<img width="943" alt="Screen Shot 2021-07-13 at 9 36 02 AM" src="https://user-images.githubusercontent.com/51519260/125463658-b9d1525e-7770-4a2e-ac72-a49ba99951c5.png">

I think we might need to either update a package or begin using a different rule like `@typescript-eslint/naming-convention` I played around a little bit with `naming-convention`, not positive it's exactly what we're looking for/gives the exact same response as `camelcase`, but it might be worth looking in to, or finding the right package to upgrade/find another package that supports the same linting behavior. 

Let me know if you have questions or want to bounce some ideas off me, David! 


[Github issue related to @typescript-eslint/camelcase](https://github.com/typescript-eslint/typescript-eslint/issues/2077)
[CHANGELOG showing camelcase support dropped](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0)

2021-07-14 14:33 UTC, dbirks commented
Hey thanks for testing it out Blake. I think we both went down the same road with regards to `naming-convention`. I did a bulk rename in a draft PR, and found that worked: https://github.com/polarislabs/aurora-service/pull/447/commits/b620fdb866b784feacc895c89da6783062fd37d3

Lemme know if you see anything else funky :man_dancing:

2021-07-15 20:54 UTC, babennettdev approved these changes
Excellent work, David! Thanks for following up re: `naming-convention`. That was the only thing I saw, and it seems to be resolved in the linked Aurora-Service PR. 👍 Great work!

2021-07-19 13:29 UTC, BWortman commented on common.js
> +    '@typescript-eslint/ban-types': ['error', {
This one is a pain b/c we have so many violations. However, I'm starting to think we may want to keep it around, even for these types. Here's some info explaining why, with examples of how to fix violations: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md

2021-07-19 14:19 UTC, dbirks commented on common.js
> +    '@typescript-eslint/ban-types': ['error', {
Chad was thinking we could ignore these for now. I hadn't took a good look at those examples of how to fix them, and they look fairly straight-forward, so I would be ok with giving the fix-up a shot. 

I'll let you guys work that decision out if you don't mind. 

cc: @camoore1979

2021-07-20 14:04 UTC, ronwarner1231 submitted a review, later dismissed

2021-07-20 14:07 UTC, dbirks commented on common.js
> +    '@typescript-eslint/ban-types': ['error', {
Updating just for documentation purposes...
We changed it to warn on everything in `@typescript-eslint/ban-types`. I tried getting it to error for Functions, and to just warn on Objects, but couldn't get eslint to do two separate things like that, so I got cleared to just warn on the entire rule.

2021-07-20 14:10 UTC, dbirks commented
Sorry it auto-dismissed your review Ron. I bumped the version to 2.0.0 which should be the last change. :ship:

2021-07-20 14:16 UTC, camoore1979 approved these changes
👍 👍

2021-07-20 14:23 UTC, BWortman commented on common.js
> +    '@typescript-eslint/ban-types': 'warn',
@camoore1979 - Shouldn't we just remove this if 'error' isn't the default? We don't want any warnings in our code. By making it an error we'll know immediately of violations (b/c it will break the build), which can be ignored where appropriate.

I'd also bump the 'warn' to 'error' on line 70, for the same reason.

Sorry for the late feedback... I haven't been focusing too much on this...

2021-07-20 14:32 UTC, camoore1979 commented on common.js
> +    '@typescript-eslint/ban-types': 'warn',
The problem is that we did not want to ban the type `Function` just yet and there is not a way to error on all other banned types while only warning on`Function`. I agree in theory and we may have to do a subsequent rollout of this as a full error, right now we're choking on getting this out the door. This is a completely new rule, so I'm ok with rolling out as a warning now and an error downstream.

2021-07-20 14:33 UTC, dbirks commented on CHANGELOG.md
> +## wip
:confused: I'm not sure how Github gave you a old version of the code in the review tab, but it looks like that's been fixed in https://github.com/polarislabs/eslint-config-polaris/pull/35/commits/83afa56467a48ad9cb192a38c6e69ad0615656c2.

2021-07-20 16:23 UTC, camoore1979 requested changes

2021-07-20 16:23 UTC, camoore1979 commented on common.js
> +    '@typescript-eslint/ban-types': 'warn',
Let's go varsity. Let's do the default `error` approach on `ban-types`. Offending repo can provide an override if absolutely necessary.
```suggestion

```

2021-07-20 16:24 UTC, tshelton5000 submitted a review, later dismissed
Thanks, @dbirks !

2021-07-20 16:50 UTC, dbirks commented on common.js
> +    '@typescript-eslint/ban-types': 'warn',
Sounds good, I'll do a force push here in a few so I can re-use the 2.0.0 tag...

2021-07-20 16:56 UTC, dbirks commented on common.js
> +    '@typescript-eslint/ban-types': 'warn',
Ok removed, so `ban-types` is back to giving errors.

2021-07-20 17:49 UTC, BWortman approved these changes
LGTM!

2021-07-21 13:13 UTC, BWortman approved these changes

2021-07-21 13:38 UTC, camoore1979 approved these changes
👍 👍

2021-07-21 13:38 UTC, merged