DIS-1648 Add linting
polarislabs/eslint-config-polaris pull request #36
Opened 2021-07-22 21:56 UTC by dbirks

This should bring no functional changes, only styling/formatting changes.

- Add a `.eslintrc.js` that extends `index.js` (to use the common configuration).
- Add husky. Looks like they've changed the way they set things up with v7. (A new `.husky` folder, and a `prepare` npm script.)
- Add Github Action to lint.
- Add the required devDependencies. This includes some typescript-eslint packages that we'll be able to remove once we do the cleanup planned in [DIS-1647](https://eoilreports.atlassian.net/browse/DIS-1647).

2021-07-27 19:10 UTC, babennettdev requested changes
Who lints the linter 👀 ? Looks like our linter lints itself 🥇 !

Great work, David. Left a couple questions, but the linting has cleaned up the repo, our Github action is working successfully, and the changes look good!

2021-07-27 19:10 UTC, babennettdev commented on .eslintrc.js
> +  // Disabling some rules for index.js due to some strange typescript errors that should be fixed in DIS-1647
👍

2021-07-27 19:10 UTC, babennettdev commented on .github/workflows/code-checks.yml
> +        run: npm run lint
Linting was performed on this PR and succeeded 👍

2021-07-27 19:10 UTC, babennettdev commented on package.json
> +    "prepare": "husky install"
What does this script do for us? I don't see where we call it, husky calls it, or our Github actions call it. Was it just used to install husky or is it used behind the scenes somewhere in the CI pipeline? If it is not used, could we remove it?

2021-07-27 19:10 UTC, babennettdev commented on package.json
> +  "version": "2.1.0-beta.0",
Don't forget to remove the `-beta` tag before merge 👀

2021-07-27 19:26 UTC, dbirks commented on package.json
> +    "prepare": "husky install"
Yes husky set that up, and I had to check the docs to double-check, but it looks like `prepare` is a reserved script name for commands you want to run on every `npm install`:
https://docs.npmjs.com/cli/v6/using-npm/scripts#life-cycle-scripts

2021-07-27 19:33 UTC, dbirks commented on package.json
> +  "version": "2.1.0-beta.0",
Updating now...

2021-07-28 15:26 UTC, babennettdev commented on package.json
> +    "prepare": "husky install"
Awesome! Thank you for the clarification!

2021-07-28 15:27 UTC, babennettdev approved these changes
LGTM, David! Thank you for clarifying on the `prepare` npm script!

2021-07-29 13:26 UTC, codetelo approved these changes
Looks great! Let's get this in!

2021-07-29 13:28 UTC, merged