DIS-1763 - Warn on unused exports
polarislabs/eslint-config-polaris pull request #39
Opened 2021-08-31 18:02 UTC by dbirks

Use the `import/no-unused-modules` rule to warn on unused exports. 

Making it apply to just `src/` and `test/`, so we don't have to ignore individual files like index.ts, .eslintrc.js, typedocs.js, ...

2021-09-01 01:07 UTC, camoore1979 requested changes

2021-09-01 01:07 UTC, camoore1979 commented on common.js
> +          "warn",
I _think_ this should be `"error"`. That's how we are enforcing most, if not all, of our ESLint rules. If necessary, an ignore can be added.

2021-09-01 01:07 UTC, camoore1979 commented
@dbirks Is there a specific beta version one can point to for evaluating this PR?

2021-09-02 13:26 UTC, dbirks commented on common.js
> +          "warn",
Ah sounds good, changing to `error`...

2021-09-02 14:16 UTC, dbirks commented
Ok pushed up a new version, with the comments, changelog, and code all changed to `error`.

Tried in horizon-pro-api, and got the same results, but as errors as expected. Used this package:
```
npm i --save-dev @polarislabs/eslint-config-polaris@2.3.0-beta.8
```

2021-09-10 18:24 UTC, camoore1979 approved these changes

2021-09-13 15:04 UTC, babennettdev requested changes
David, I have consumed this package locally in many of our repos, `HPAPI`, `aurora-client` and `service`, and `polaris-nest-core` and `polaris-components`. All reported varying results when running `npm run lint` depending on the number of unused exports. I think this will be a great opportunity to clean up our repos as we begin consuming this package.

My only recommendation is that we also exclude `**/*.stories.tsx` as well for `polaris-components` as these need to use default exports to run Storybook, but don't get consumed directly anywhere in the repository. All other eslint errors I saw seemed valid and will need to be rectified as we consume this version of the package in our repos.

2021-09-13 15:04 UTC, babennettdev commented on common.js
> +      ],
```suggestion
      excludedFiles: [
        "**/*.spec.ts",
        "**/*.spec.tsx",
        "**/*.stories.tsx",
        "**/*.test.ts",
        "**/*.test.tsx",
        "index.ts",
        "index.tsx",
        "main.ts",
        "src/pages/**",
      ],
```

2021-09-13 15:13 UTC, dbirks commented on common.js
> +      ],
Sounds good to me :+1: 
I'll get the changelog updated too to fix the merge conflict...

2021-09-13 15:22 UTC, dbirks commented
I'm sorry, this repo is currently in an in-between state with some Github Actions for the release process. I'll finish up my changes to that today, and will re-add you both when it's ready for a final review.

2021-09-13 20:05 UTC, babennettdev commented
Sounds good @dbirks let me know when this is ready for another look!

2021-09-15 16:59 UTC, dbirks commented
Ok, this should be finally ready for a second look. I've got a new beta out as well, ignoring `**/*.stories.tsx`:
```
npm i --save-dev @polarislabs/eslint-config-polaris@2.3.0-beta.9
```

2021-09-15 18:06 UTC, babennettdev approved these changes
LGTM, David! Thank you for making the requested change!

Make sure you remove the `-beta.9` from the version before merge! 🚀

2021-09-16 17:00 UTC, camoore1979 approved these changes

2021-09-16 17:03 UTC, dbirks commented
Thanks guys :+1: 
I just confirmed locally that running `npm version minor` bumps it up to 2.3.0 correctly, so I'll give it a merge...

2021-09-16 17:04 UTC, merged