DEVOPS-715 - Auto-publish package betas
polarislabs/eslint-config-polaris pull request #55
Opened 2022-01-03 16:52 UTC by dbirks

- Auto-publish a beta package whenever Code Checks completes successfully.
- Switch Actions to use a reusable workflow from the new polarislabs/actions repo.
- Remove the First Time Greeting, PR Labeler, and Changelog Reminder Actions, since we're wanting to reduce our Github Actions minutes where it's easy to do so.

---

*This change was executed automatically with [Shepherd](https://github.com/NerdWalletOSS/shepherd).* 💚🤖

2022-01-05 16:27 UTC, camoore1979 requested changes

2022-01-05 16:27 UTC, camoore1979 commented on .github/workflows/code-checks.yml
> +      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
I wouldn't run `publish-beta` unless `code-checks` exits successfully. Is that implicitly handled by the order of the jobs here? Or, do you have to provide explicit configuration for that?

2022-01-05 16:27 UTC, camoore1979 commented on .github/workflows/code-checks.yml
I would rename this workflow to be `run-code-checks-and-publish-beta`.

2022-01-05 16:29 UTC, dbirks commented on .github/workflows/code-checks.yml
> +      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
Yeah I had to add that `needs` keyword to have it be dependent on the other. (Some [docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idneeds))

2022-01-12 13:45 UTC, dbirks commented on .github/workflows/code-checks.yml
Ok got these up to date finally. Pushed out to all the other repos in this PR too.

2022-01-12 13:47 UTC, dbirks commented
Force-pushing one more time, since this was in draft before, and the Actions didn't run...

2022-01-18 19:54 UTC, camoore1979 approved these changes

2022-01-19 15:57 UTC, codetelo approved these changes

2022-01-19 19:35 UTC, merged